### ISSUE TITLE
Cant get temp from mysql.

### ISSUE THREAD

**Issue by kivimart** [rebtor/nl.rebtor.sql#3]
Hello i cant get the temp in from mariadb 10.*

This is my command;
SELECT state as temp FROM states WHERE entity_id LIKE "sensor.191_temperature" ORDER BY created DESC LIMIT 1.
It works if i type it in MySQL.
Can you see whats wrong in my query.

Another thing that i found was wen i create a new MySQL weather entry then the text in the follow the instruction says power and meter;  Enter serverdetails below. Make sure the Query returns one row with 2 collums Power and Meter

Tanks in advance

**Comment by kivimart** [comment]
I cant see any connection from homey to the database, i have checked so that i can connect with the same account from other machines in the same network.

**Comment by rebtor** [comment]
Hi Kivimart,

Sorry for the untimely reaction. 

I changed the text. The change awaits athoms stamp. 

As for why there is no connection with the mysql server that can have a 1000 reasons. You might try to use an IP address in-staid of DNS name for the server. 

Also the weather device also expects a fieldname for humidity. It might help to just fill it with blank or 0. 

hope this helps.
