### ISSUE TITLE
Weer app krijgt geen data.

### ISSUE THREAD

**Issue by goten007** [rebtor/nl.rebtor.sql#4]
Ik heb een Mysql server draaien.
Ik heb daar de een tabel aangemaakt weer met de volgende velden (id,) temp and humidity.
Deze benamingen ben ik tegen gekomen op het internet.
Voor mijn is het ook duidelijk wat ik moet invullen bij Host, Gebruiker, Wachtwoord en Database.
Ik heb bij Query het volgende gezet SELECT * FROM weer WHERE id='1'

Op mijn Mysql server wordt regelmatig id 1 geupdate met de juiste temp en humidity.
Maar deze gegevens krijg ik niet te zien op mijn Homey.

**Comment by rebtor** [comment]
Hallo Goten007,

Heb je dit inmiddels al opgelost. Met de laatste versie en homey 2.0 kan ik gewoon data uit een MySQL tabel halen met een weather device met de volgende query:

select p1_current_power_in * 1000 as temp, p1_meterreading_in_1 +  p1_meterreading_in_2 as humidity FROM Domotica.p1_log  order by p1_timestamp desc  limit 1
